### ISSUE TITLE
[Feature] Local SQLite DB

### ISSUE THREAD

**Issue by AndiRen** [Development-Corps/FeedFusion#11]
### Describe the Feature

Use a local SQLite DB to store user feed data

### **Requirements**

- [ ] Create an initial DB and relevant data tables
- [ ] Insert article/category info, etc. into relevant data
- [ ] Allow for update for new articles/categories
- [ ] Update read, priority, and other tags, etc.

**Comment by LunarVagabond** [comment]
@AndiRen 
I'm spit balling here but I think the DB needs the following tables / columns

1. `feeds`
    - `feed_id`: Primary key because why not
    - `url`: the access url for feed 
    - `alias` [Optional]: the display name of the feed (instead of just displaying the url
    - `poll_interval`: the time to wait before pulling / checking for new items in the feed
    - `feed_type`: One of either `RSS` or `ATOM`
    - `category`: Foreign key references `categories` table to sort on in the front end
2. `categories`
    - `category_id`: for reference
    - `name`: the name to display back to the user
    - `sort_order`: I don’t know about this one but I think we could leverage it to sort the front end in some way (we may want to do this with feeds too again I don’t know)
    - `parent_category`: Another maybe but I think we might be able to nest the categories ❓

I'm probably missing some things here but I think with these tables we would have a solid foundation

**Comment by LunarVagabond** [comment]
Oh we should also probably add 

3. `feed_items`
    - `feed_item_id`: PK
    - `content`: Blob the stuff of a single element
    - `feed_id`: FK to feeds table

**Comment by AndiRen** [comment]
Totally! Looks like a good set of tables. Articles could also maybe be in there. May need a join table between feeds/categories and articles so there could be many categories an article belonged to.
